theme:           jekyll-theme-cayman
title:           Match the Numbers
description:     Try to make all numbers equal by visiting them
is_user_page:    false
is_project_page: true
show_downloads:  true
